/**
 * Knowledge brain, Dental Med Austria's real Instagram voice, distilled.
 *
 * Built from the scraped @dentalmedaustria archive (1,000+ posts, 200+ video
 * transcripts, captions, engagement) tagged with the treatment/technology
 * taxonomy. Mirrors the clinic-knowledge.ts retrieval pattern so it plugs into
 * the chatbot (grounding) and AutoSEO (real phrasing + content emphasis).
 *
 * Corpus is regenerated by DMA-INSTAGRAM-SCRAPE/brain_gen.py.
 */
import corpusJson from "./brain-corpus.json";

export type BrainSnippet = { url: string; lang: string | null; text: string };

export type BrainPost = {
  id: string;
  shortcode: string;
  type: string; // posts | highlights | stories
  author: string;
  date: string;
  url: string;
  caption: string;
  transcript: string;
  summary: string;
  language: string | null;
  likes: number | null;
  location: string | null;
  tagged: string[];
  treatments: string[];
  technologies: string[];
  n_media: number;
  n_video: number;
};

export type BrainTopic = {
  treatment: string;
  post_count: number;
  languages: string[];
  total_likes: number;
  example_snippets: BrainSnippet[];
};

export type BrainCorpus = {
  meta: {
    source: string;
    posts: number;
    posts_with_transcript: number;
    topics: number;
    treatments_covered: string[];
  };
  topics: BrainTopic[];
  posts: BrainPost[];
};

export const BRAIN = corpusJson as unknown as BrainCorpus;

const STOPWORDS = new Set(
  "a an and are as at be by for from has have how in is it its of on or that the to was what when where which who will with your you our we".split(" "),
);

function tokenize(s: string): string[] {
  return (s || "")
    .toLowerCase()
    .replace(/[^a-z0-9äöüßàèéìíòóùúçë+ ]/gi, " ")
    .split(/\s+/)
    .filter((t) => t.length >= 2 && !STOPWORDS.has(t));
}

// Pre-tokenise once at module load. "strong" = caption + tags (high signal),
// "body" = transcript (lower weight).
const INDEX = BRAIN.posts.map((post) => ({
  post,
  strong: new Set(tokenize([post.caption, ...post.treatments, ...post.technologies].join(" "))),
  body: new Set(tokenize(post.transcript)),
}));

export type ScoredBrainPost = { post: BrainPost; score: number };

/** Retrieve DMA Instagram posts most relevant to a free-text query. */
export function searchBrain(query: string, limit = 5): ScoredBrainPost[] {
  const terms = tokenize(query);
  if (terms.length === 0) return [];
  const scored: ScoredBrainPost[] = [];
  for (const row of INDEX) {
    let score = 0;
    for (const term of terms) {
      if (row.strong.has(term)) score += 3;
      if (row.body.has(term)) score += 1;
    }
    // Small popularity nudge so we surface posts that actually resonated.
    if (score > 0 && row.post.likes) score += Math.min(2, Math.log10(row.post.likes + 1));
    if (score > 0) scored.push({ post: row.post, score });
  }
  scored.sort((a, b) => b.score - a.score);
  return scored.slice(0, limit);
}

/** Topic aggregation for a treatment concept (fuzzy match on the label). */
export function getBrainTopic(concept: string): BrainTopic | undefined {
  const c = concept.toLowerCase();
  return (
    BRAIN.topics.find((t) => t.treatment.toLowerCase() === c) ||
    BRAIN.topics.find((t) => t.treatment.toLowerCase().includes(c) || c.includes(t.treatment.toLowerCase()))
  );
}

/** Format brain hits as CONTEXT passages for the chatbot prompt. */
export function brainGroundingFor(query: string, limit = 3): string {
  const hits = searchBrain(query, limit);
  if (!hits.length) return "";
  return hits
    .map((h, i) => {
      const tags = h.post.treatments.slice(0, 4).join(", ");
      const body = (h.post.transcript || h.post.caption).slice(0, 320).replace(/\s+/g, " ").trim();
      return `[IG${i + 1}] ${h.post.summary}${tags ? ` (${tags})` : ""}\n${body}\n${h.post.url}`;
    })
    .join("\n\n");
}

/**
 * Real-content context block for AutoSEO: what DMA actually publishes about
 * this keyword/concept, topic stats + real caption/transcript snippets in the
 * clinic's own voice. Grounds generated articles in the brand's real emphasis.
 */
export function brainContextForKeyword(keyword: string, secondary: string[] = []): string {
  const query = [keyword, ...secondary].join(" ");
  const hits = searchBrain(query, 4);
  const topic = getBrainTopic(keyword) || getBrainTopic(query);
  const lines: string[] = [];
  if (topic) {
    lines.push(
      `Dental Med Austria's Instagram emphasises "${topic.treatment}" heavily: ${topic.post_count} posts, ${topic.total_likes.toLocaleString()} total likes, in ${topic.languages.join("/")}.`,
    );
  }
  if (hits.length) {
    lines.push("Real snippets from the clinic's own posts (match this voice, do not quote verbatim):");
    for (const h of hits.slice(0, 4)) {
      const s = (h.post.caption || h.post.transcript).slice(0, 200).replace(/\s+/g, " ").trim();
      if (s) lines.push(`- ${s}`);
    }
  }
  return lines.join("\n");
}
